[general]
live_config_reload = true
ipc_socket = false

[window]
opacity = 1
blur = true

[colors]
draw_bold_text_with_bright_colors = true
primary.background = "#000000"

[cursor]
style = {shape = "Block", blinking = "On"}

[font]
size = 10
# normal = {family = "monospace", style = "Bold"}

[mouse]
hide_when_typing = true

# keyboard.bindings = [
#   {key = "ArrowUp", mods = "Shift", mode = "Search", action = "ScrollPageUp"},
#   {key = "ArrowDown", mods = "Shift", mode = "Search", action = "ScrollPageDown"}
# ]
