$term = kitty
$menu = rofi -show run

$mod = Alt

exec-once = lxsession
exec-once = pulseaudio

exec-once = waypaper --restore
exec-once = nwg-panel

# Apple numeric keyboard layout

bind = $mod, Return, exec, kitty
bind = $mod, q, killactive,
bind = $mod, c, exec, hyprctl reload

bind = , XF86LaunchB, exec, $menu

bind = , XF86Launch7, exec, gtklock
bind = , XF86Launch8, exec, systemctl suspend
bind = , XF86Launch9, exec, reboot
bind = , NoSymbol, exec, shutdown now

bind = $mod, Left, workspace, e-1
bind = $mod, Right, workspace, e+1

bind = $mod, z, cyclenext

animations {
    enabled = 0
}

misc {
    disable_hyprland_logo = true
    force_default_wallpaper = 0
    background_color = 0x222222
}

workspace = 1, persistent:true
workspace = 2, persistent:true
workspace = 3, persistent:true
workspace = 4, persistent:true
workspace = 5, persistent:true
workspace = 6, persistent:true
workspace = 7, persistent:true
workspace = 8, persistent:true
workspace = 9, persistent:true
